# Manipulating Arrays

Here are two techniques that can be used to change or manipulayte the structure of arrays:
*  Stacking
*  Reshaping

### Stacking

In [1]:
#importing the NumPy library
import numpy as np

# Creating two 1-D arrays with 5 elements using arange
arr_1 = np.arange(0,5)
arr_2 = np.arange(5,10)


In [2]:
# Horizonal stacking - Appending the elements in the same row
np.hstack((arr_1,arr_2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Vertical stacking - Increasing the number of row
np.vstack((arr_1,arr_2))

# Storing the stacked array for further operations
arr_3 = np.vstack((arr_1,arr_2))

In [5]:
# Checking the dimensions of the array
arr_3.ndim

2

In [9]:
# Printing the created array
arr_3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
# Number of rows and columns in the array
arr_3.shape

(2, 5)

### Reshaping

In [11]:
# Creating an array of first ten natural numbers
arr_4 = np.arange(1,11)

# Printing the created array
arr_4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# Reshaping the 1D array into a 2D array with 2 elements in five rows
arr_5 =arr_4.reshape(5,2) 

In [18]:
# Checking the rows and columns in the created array
arr_5.shape

(5, 2)

In [20]:
# Creating a 2D array with 4 elements in five rows (elements from 20 to 39)
arr_6 = np.arange(20,40).reshape(5,4)

# Checking the rows and columns in the created array
arr_6

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [21]:
# Stacking arr_5 and arr_6
np.vstack(arr_5,arr_6)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [22]:
# Check the structure of arr_6
arr_6.shape

(5, 4)

In [23]:
# Reshape the arr_6 to vertically stack with arr_5 
arr_6 = np.arange(20,40).reshape(10,2)
arr_6

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [25]:
# Stacking arr_5 and arr_6
np.vstack((arr_5,arr_6))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [26]:
p=[[1, 5],
 [3, 7],
 [4, 9]]

In [27]:
np.reshape(p, -1)

array([1, 5, 3, 7, 4, 9])

In [31]:
array_1=[[1, 2, 3, 4, 5]
       [6, 7, 8, 9, 10]
       [11, 12, 13, 14, 15]
       [16, 17, 18, 19, 20]]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\moury\AppData\Local\Temp\ipykernel_19880\2369176169.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1=[[1, 2, 3, 4, 5]
C:\Users\moury\AppData\Local\Temp\ipykernel_19880\2369176169.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1=[[1, 2, 3, 4, 5]
C:\Users\moury\AppData\Local\Temp\ipykernel_19880\2369176169.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1=[[1, 2, 3, 4, 5]
C:\Users\moury\AppData\Local\Temp\ipykernel_19880\2369176169.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  array_1=[[1, 2, 3, 4, 5]
C:\Users\moury\AppData\Local\Temp\ipykerne

TypeError: list indices must be integers or slices, not tuple

In [4]:
array_1=[[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

In [5]:
print(array_1.reshape(5, 4)[array_1%2 != 0])

AttributeError: 'list' object has no attribute 'reshape'

In [6]:
print(array_1[array_1%2 != 0])

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [7]:
print(array_1[array_1%2 == 0].reshape(5, 2))

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [10]:
print(array_1[array_1 % 2 != 0].reshape(5, 2))

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [11]:
1%2

1

In [14]:
import numpy as np
p=[[1, 5],
 [3, 7],
 [4, 9]]

In [15]:
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])